### PR TITLE
Search range clear

### PR DESCRIPTION
**Pull request by kw00183**

### CODE REVIEW

**Comment by kw00183** [comment]
I have the clear search and dates search in the different search forms now. This should satisfy his additional asks on iteration 2. unit tests are added and pass

**Comment by kw00183** [comment]
made the datepicker read only and set the session variables to nil on before action

**Comment by kw00183** [comment]
I added additional logic in the index to treat empty date entries like a clear

**Comment by asuratte** [comment]
Looks great! Clear button returns all reports & clears last search from session, searches are cleared upon navigating to new page, date feature returns reports within dates or message if no results. Merging in.

**Pull request merged**
